name: Update urls

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # 北京时间每天 2 点执行

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download URLs and upload to Gist
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
        URLS: ${{ secrets.URLS }}
      run: |
        for url in $URLS; do
          filename="$(echo $url | sed 's~http[s]*://~~g' | sed 's~www\.~~g').txt"
          curl -o $filename $url
          cat $filename
          # gist_url=$(curl -s -X POST https://api.github.com/gists -H "Authorization: Bearer $MY_TOKEN" -H "Content-Type: application/json" -d '{"files": {"'$filename'": {"content": "'$(cat $filename)'"}}, "public": true}' | grep -o '"html_url": ".*"' | cut -d'"' -f4)
          gist_url=$(curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $MY_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/gists -d "{\"public\":false,\"files\":{\"$filename\":{\"content\":\"$(cat "$filename" | tr -d '\r' | sed 's/\"/\\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\"}}}")
          # echo $(curl -s -X POST https://api.github.com/gists -H "Authorization: Bearer $MY_TOKEN" -H "Content-Type: application/json" -d '{"files": {"'$filename'": {"content": "'$(cat $filename)'"}}, "public": true}')
          echo "$filename: $gist_url"
        done
