name: Update urls

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # 北京时间每天 2 点执行

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download URLs and upload to Gist
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
        URLS: ${{ secrets.URLS }}
      run: |
        for url in $URLS; do
          filename="$(echo "$url" | awk -F/ '{match($3, /[^\.]+\.[^\.]+$/); print substr($3, RSTART)}').txt"
          data="{\"public\":false, \"files\":{\"$filename\":{\"content\":\"$(cat "$filename" |  sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\"}}}"
          echo "$data" > data.json
          curl -o $filename $url
          head $filename
          gist_url=$(curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/gists -d "@data.json")
          # echo $(echo $gist_url | grep -o '"html_url": ".*"' | cut -d'"' -f4)
          echo $gist_url
        done
