name: Update urls

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # 北京时间每天 2 点执行

jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch URLs
      run: |
        # Fetch URLs
        URLS=$URLS_SECRET
        for url in "${URLS[@]}"; do
          domain=$(echo "$url" | sed -e 's|https://||' -e 's|http://||' -e 's|www\.||' -e 's|/.*||')
          curl "$url" > "$domain"
        done

    - name: Upload files to Gist
      uses: github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs')
          const path = require('path')

          const files = fs.readdirSync('.').filter(file => file !== '.git' && file !== '.' && file !== '..')
          const promises = files.map(async file => {
            const content = fs.readFileSync(file, 'utf8')
            const filename = path.basename(file)
            const response = await github.gists.create({
              files: {
                [filename]: {
                  content: content
                }
              },
              public: false
            })
            console.log(`Created Gist: ${response.data.html_url}`)
          })

          await Promise.all(promises)
      env:
        URLS_SECRET: ${{ secrets.URLS }}
